server {
    listen 80;
    server_name _;

    # 프론트엔드 React 화면 서빙
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # React Router(SPA) 새로고침 에러 방지
        try_files $uri $uri/ /index.html;
    }

    # /api/ 로 시작하는 요청은 전부 백엔드(3000번) 컨테이너로 전달
    location /api/ {
        proxy_pass http://backend:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # (필요시) AI 통신용 포트 라우팅 예시 (STT 서버 등)
    # location /ai/stt/ {
    #     proxy_pass http://server_ai_stt:8001;
    # }
}
