//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class ErrorReportMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/ErrorReport";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public string error_id;
        public string task_id;
        public string component;
        public uint code;
        public byte severity;
        public string message;
        public bool recoverable;
        public const byte SEVERITY_INFO = 0;
        public const byte SEVERITY_WARN = 1;
        public const byte SEVERITY_ERROR = 2;
        public const byte SEVERITY_FATAL = 3;

        public ErrorReportMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.error_id = "";
            this.task_id = "";
            this.component = "";
            this.code = 0;
            this.severity = 0;
            this.message = "";
            this.recoverable = false;
        }

        public ErrorReportMsg(BuiltinInterfaces.TimeMsg stamp, string error_id, string task_id, string component, uint code, byte severity, string message, bool recoverable)
        {
            this.stamp = stamp;
            this.error_id = error_id;
            this.task_id = task_id;
            this.component = component;
            this.code = code;
            this.severity = severity;
            this.message = message;
            this.recoverable = recoverable;
        }

        public static ErrorReportMsg Deserialize(MessageDeserializer deserializer) => new ErrorReportMsg(deserializer);

        private ErrorReportMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.error_id);
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.component);
            deserializer.Read(out this.code);
            deserializer.Read(out this.severity);
            deserializer.Read(out this.message);
            deserializer.Read(out this.recoverable);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.error_id);
            serializer.Write(this.task_id);
            serializer.Write(this.component);
            serializer.Write(this.code);
            serializer.Write(this.severity);
            serializer.Write(this.message);
            serializer.Write(this.recoverable);
        }

        public override string ToString()
        {
            return "ErrorReportMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nerror_id: " + error_id.ToString() +
            "\ntask_id: " + task_id.ToString() +
            "\ncomponent: " + component.ToString() +
            "\ncode: " + code.ToString() +
            "\nseverity: " + severity.ToString() +
            "\nmessage: " + message.ToString() +
            "\nrecoverable: " + recoverable.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
