//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class HeartbeatMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/Heartbeat";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public string robot_id;
        public string node_name;
        public uint seq;
        public byte health_state;
        public string active_task_id;
        public const byte HEALTH_ONLINE = 0;
        public const byte HEALTH_DEGRADED = 1;
        public const byte HEALTH_OFFLINE = 2;

        public HeartbeatMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.robot_id = "";
            this.node_name = "";
            this.seq = 0;
            this.health_state = 0;
            this.active_task_id = "";
        }

        public HeartbeatMsg(BuiltinInterfaces.TimeMsg stamp, string robot_id, string node_name, uint seq, byte health_state, string active_task_id)
        {
            this.stamp = stamp;
            this.robot_id = robot_id;
            this.node_name = node_name;
            this.seq = seq;
            this.health_state = health_state;
            this.active_task_id = active_task_id;
        }

        public static HeartbeatMsg Deserialize(MessageDeserializer deserializer) => new HeartbeatMsg(deserializer);

        private HeartbeatMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.node_name);
            deserializer.Read(out this.seq);
            deserializer.Read(out this.health_state);
            deserializer.Read(out this.active_task_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.robot_id);
            serializer.Write(this.node_name);
            serializer.Write(this.seq);
            serializer.Write(this.health_state);
            serializer.Write(this.active_task_id);
        }

        public override string ToString()
        {
            return "HeartbeatMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nrobot_id: " + robot_id.ToString() +
            "\nnode_name: " + node_name.ToString() +
            "\nseq: " + seq.ToString() +
            "\nhealth_state: " + health_state.ToString() +
            "\nactive_task_id: " + active_task_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
