//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class ModuleStateMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/ModuleState";
        public override string RosMessageName => k_RosMessageName;

        public byte module_type;
        public bool is_available;
        public bool is_on;
        public byte level;
        public byte health;
        public string reason;
        public const byte MODULE_NONE = 0;
        public const byte MODULE_AIR_PURIFIER = 1;
        public const byte MODULE_HUMIDIFIER = 2;
        public const byte MODULE_DEHUMIDIFIER = 3;
        public const byte HEALTH_OK = 0;
        public const byte HEALTH_WARN = 1;
        public const byte HEALTH_FAULT = 2;

        public ModuleStateMsg()
        {
            this.module_type = 0;
            this.is_available = false;
            this.is_on = false;
            this.level = 0;
            this.health = 0;
            this.reason = "";
        }

        public ModuleStateMsg(byte module_type, bool is_available, bool is_on, byte level, byte health, string reason)
        {
            this.module_type = module_type;
            this.is_available = is_available;
            this.is_on = is_on;
            this.level = level;
            this.health = health;
            this.reason = reason;
        }

        public static ModuleStateMsg Deserialize(MessageDeserializer deserializer) => new ModuleStateMsg(deserializer);

        private ModuleStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.module_type);
            deserializer.Read(out this.is_available);
            deserializer.Read(out this.is_on);
            deserializer.Read(out this.level);
            deserializer.Read(out this.health);
            deserializer.Read(out this.reason);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.module_type);
            serializer.Write(this.is_available);
            serializer.Write(this.is_on);
            serializer.Write(this.level);
            serializer.Write(this.health);
            serializer.Write(this.reason);
        }

        public override string ToString()
        {
            return "ModuleStateMsg: " +
            "\nmodule_type: " + module_type.ToString() +
            "\nis_available: " + is_available.ToString() +
            "\nis_on: " + is_on.ToString() +
            "\nlevel: " + level.ToString() +
            "\nhealth: " + health.ToString() +
            "\nreason: " + reason.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
