//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class ModuleOperationEventMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/ModuleOperationEvent";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public string task_id;
        public string command_id;
        public byte module_type;
        public bool power_on;
        public byte level;
        public byte state;
        public bool success;
        public string message;
        public const byte STATE_REQUESTED = 0;
        public const byte STATE_APPLIED = 1;
        public const byte STATE_FAILED = 2;

        public ModuleOperationEventMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.task_id = "";
            this.command_id = "";
            this.module_type = 0;
            this.power_on = false;
            this.level = 0;
            this.state = 0;
            this.success = false;
            this.message = "";
        }

        public ModuleOperationEventMsg(BuiltinInterfaces.TimeMsg stamp, string task_id, string command_id, byte module_type, bool power_on, byte level, byte state, bool success, string message)
        {
            this.stamp = stamp;
            this.task_id = task_id;
            this.command_id = command_id;
            this.module_type = module_type;
            this.power_on = power_on;
            this.level = level;
            this.state = state;
            this.success = success;
            this.message = message;
        }

        public static ModuleOperationEventMsg Deserialize(MessageDeserializer deserializer) => new ModuleOperationEventMsg(deserializer);

        private ModuleOperationEventMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.command_id);
            deserializer.Read(out this.module_type);
            deserializer.Read(out this.power_on);
            deserializer.Read(out this.level);
            deserializer.Read(out this.state);
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.task_id);
            serializer.Write(this.command_id);
            serializer.Write(this.module_type);
            serializer.Write(this.power_on);
            serializer.Write(this.level);
            serializer.Write(this.state);
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "ModuleOperationEventMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\ntask_id: " + task_id.ToString() +
            "\ncommand_id: " + command_id.ToString() +
            "\nmodule_type: " + module_type.ToString() +
            "\npower_on: " + power_on.ToString() +
            "\nlevel: " + level.ToString() +
            "\nstate: " + state.ToString() +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
