//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class ModuleSwapEventMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/ModuleSwapEvent";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public string task_id;
        public string command_id;
        public byte from_module_type;
        public byte to_module_type;
        public byte state;
        public bool success;
        public string message;
        public const byte STATE_REQUESTED = 0;
        public const byte STATE_MOVING_TO_HQ = 1;
        public const byte STATE_ARRIVED_HQ = 2;
        public const byte STATE_SWAPPING = 3;
        public const byte STATE_COMPLETED = 4;
        public const byte STATE_FAILED = 5;

        public ModuleSwapEventMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.task_id = "";
            this.command_id = "";
            this.from_module_type = 0;
            this.to_module_type = 0;
            this.state = 0;
            this.success = false;
            this.message = "";
        }

        public ModuleSwapEventMsg(BuiltinInterfaces.TimeMsg stamp, string task_id, string command_id, byte from_module_type, byte to_module_type, byte state, bool success, string message)
        {
            this.stamp = stamp;
            this.task_id = task_id;
            this.command_id = command_id;
            this.from_module_type = from_module_type;
            this.to_module_type = to_module_type;
            this.state = state;
            this.success = success;
            this.message = message;
        }

        public static ModuleSwapEventMsg Deserialize(MessageDeserializer deserializer) => new ModuleSwapEventMsg(deserializer);

        private ModuleSwapEventMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.task_id);
            deserializer.Read(out this.command_id);
            deserializer.Read(out this.from_module_type);
            deserializer.Read(out this.to_module_type);
            deserializer.Read(out this.state);
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.task_id);
            serializer.Write(this.command_id);
            serializer.Write(this.from_module_type);
            serializer.Write(this.to_module_type);
            serializer.Write(this.state);
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "ModuleSwapEventMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\ntask_id: " + task_id.ToString() +
            "\ncommand_id: " + command_id.ToString() +
            "\nfrom_module_type: " + from_module_type.ToString() +
            "\nto_module_type: " + to_module_type.ToString() +
            "\nstate: " + state.ToString() +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
