//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class RobotStatusMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/RobotStatus";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public string robot_id;
        public byte mode;
        public byte task_state;
        public string active_task_id;
        public Geometry.PoseStampedMsg pose;
        public float battery_pct;
        public bool is_charging;
        public byte safety_state;
        public uint last_error_code;
        public const byte MODE_IDLE = 0;
        public const byte MODE_MANUAL = 1;
        public const byte MODE_AUTONOMOUS = 2;
        public const byte MODE_DOCKING = 3;
        public const byte MODE_ERROR = 4;
        public const byte TASK_NONE = 0;
        public const byte TASK_RECEIVED = 1;
        public const byte TASK_VALIDATING = 2;
        public const byte TASK_ACCEPTED = 3;
        public const byte TASK_MOVING = 4;
        public const byte TASK_ARRIVED = 5;
        public const byte TASK_EXECUTING_MODULE = 6;
        public const byte TASK_RETURNING = 7;
        public const byte TASK_COMPLETED = 8;
        public const byte TASK_FAILED = 9;
        public const byte TASK_CANCELED = 10;
        public const byte SAFETY_NORMAL = 0;
        public const byte SAFETY_WARN = 1;
        public const byte SAFETY_ESTOP = 2;

        public RobotStatusMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.robot_id = "";
            this.mode = 0;
            this.task_state = 0;
            this.active_task_id = "";
            this.pose = new Geometry.PoseStampedMsg();
            this.battery_pct = 0.0f;
            this.is_charging = false;
            this.safety_state = 0;
            this.last_error_code = 0;
        }

        public RobotStatusMsg(BuiltinInterfaces.TimeMsg stamp, string robot_id, byte mode, byte task_state, string active_task_id, Geometry.PoseStampedMsg pose, float battery_pct, bool is_charging, byte safety_state, uint last_error_code)
        {
            this.stamp = stamp;
            this.robot_id = robot_id;
            this.mode = mode;
            this.task_state = task_state;
            this.active_task_id = active_task_id;
            this.pose = pose;
            this.battery_pct = battery_pct;
            this.is_charging = is_charging;
            this.safety_state = safety_state;
            this.last_error_code = last_error_code;
        }

        public static RobotStatusMsg Deserialize(MessageDeserializer deserializer) => new RobotStatusMsg(deserializer);

        private RobotStatusMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.robot_id);
            deserializer.Read(out this.mode);
            deserializer.Read(out this.task_state);
            deserializer.Read(out this.active_task_id);
            this.pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.battery_pct);
            deserializer.Read(out this.is_charging);
            deserializer.Read(out this.safety_state);
            deserializer.Read(out this.last_error_code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.robot_id);
            serializer.Write(this.mode);
            serializer.Write(this.task_state);
            serializer.Write(this.active_task_id);
            serializer.Write(this.pose);
            serializer.Write(this.battery_pct);
            serializer.Write(this.is_charging);
            serializer.Write(this.safety_state);
            serializer.Write(this.last_error_code);
        }

        public override string ToString()
        {
            return "RobotStatusMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nrobot_id: " + robot_id.ToString() +
            "\nmode: " + mode.ToString() +
            "\ntask_state: " + task_state.ToString() +
            "\nactive_task_id: " + active_task_id.ToString() +
            "\npose: " + pose.ToString() +
            "\nbattery_pct: " + battery_pct.ToString() +
            "\nis_charging: " + is_charging.ToString() +
            "\nsafety_state: " + safety_state.ToString() +
            "\nlast_error_code: " + last_error_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
