//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class RobotCommandMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/RobotCommand";
        public override string RosMessageName => k_RosMessageName;

        public string command_id;
        public BuiltinInterfaces.TimeMsg issued_at;
        public byte command_type;
        public string target_zone;
        public Geometry.PoseStampedMsg target_pose;
        public byte module_type;
        public bool module_power;
        public byte module_level;
        public uint max_exec_sec;
        public const byte COMMAND_MOVE = 0;
        public const byte COMMAND_MODULE = 1;
        public const byte COMMAND_STOP = 2;
        public const byte COMMAND_CANCEL = 3;
        public const byte COMMAND_RETURN = 4;
        public const byte MODULE_NONE = 0;
        public const byte MODULE_AIR_PURIFIER = 1;
        public const byte MODULE_HUMIDIFIER = 2;
        public const byte MODULE_DEHUMIDIFIER = 3;

        public RobotCommandMsg()
        {
            this.command_id = "";
            this.issued_at = new BuiltinInterfaces.TimeMsg();
            this.command_type = 0;
            this.target_zone = "";
            this.target_pose = new Geometry.PoseStampedMsg();
            this.module_type = 0;
            this.module_power = false;
            this.module_level = 0;
            this.max_exec_sec = 0;
        }

        public RobotCommandMsg(string command_id, BuiltinInterfaces.TimeMsg issued_at, byte command_type, string target_zone, Geometry.PoseStampedMsg target_pose, byte module_type, bool module_power, byte module_level, uint max_exec_sec)
        {
            this.command_id = command_id;
            this.issued_at = issued_at;
            this.command_type = command_type;
            this.target_zone = target_zone;
            this.target_pose = target_pose;
            this.module_type = module_type;
            this.module_power = module_power;
            this.module_level = module_level;
            this.max_exec_sec = max_exec_sec;
        }

        public static RobotCommandMsg Deserialize(MessageDeserializer deserializer) => new RobotCommandMsg(deserializer);

        private RobotCommandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.command_id);
            this.issued_at = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.command_type);
            deserializer.Read(out this.target_zone);
            this.target_pose = Geometry.PoseStampedMsg.Deserialize(deserializer);
            deserializer.Read(out this.module_type);
            deserializer.Read(out this.module_power);
            deserializer.Read(out this.module_level);
            deserializer.Read(out this.max_exec_sec);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.command_id);
            serializer.Write(this.issued_at);
            serializer.Write(this.command_type);
            serializer.Write(this.target_zone);
            serializer.Write(this.target_pose);
            serializer.Write(this.module_type);
            serializer.Write(this.module_power);
            serializer.Write(this.module_level);
            serializer.Write(this.max_exec_sec);
        }

        public override string ToString()
        {
            return "RobotCommandMsg: " +
            "\ncommand_id: " + command_id.ToString() +
            "\nissued_at: " + issued_at.ToString() +
            "\ncommand_type: " + command_type.ToString() +
            "\ntarget_zone: " + target_zone.ToString() +
            "\ntarget_pose: " + target_pose.ToString() +
            "\nmodule_type: " + module_type.ToString() +
            "\nmodule_power: " + module_power.ToString() +
            "\nmodule_level: " + module_level.ToString() +
            "\nmax_exec_sec: " + max_exec_sec.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
