//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Robot
{
    [Serializable]
    public class SensorStateMsg : Message
    {
        public const string k_RosMessageName = "robot_msgs/SensorState";
        public override string RosMessageName => k_RosMessageName;

        public BuiltinInterfaces.TimeMsg stamp;
        public string source;
        public float temperature_c;
        public float humidity_pct;
        public float pm25;
        public float obstacle_dist_m;
        public float localization_score;
        public bool is_valid;

        public SensorStateMsg()
        {
            this.stamp = new BuiltinInterfaces.TimeMsg();
            this.source = "";
            this.temperature_c = 0.0f;
            this.humidity_pct = 0.0f;
            this.pm25 = 0.0f;
            this.obstacle_dist_m = 0.0f;
            this.localization_score = 0.0f;
            this.is_valid = false;
        }

        public SensorStateMsg(BuiltinInterfaces.TimeMsg stamp, string source, float temperature_c, float humidity_pct, float pm25, float obstacle_dist_m, float localization_score, bool is_valid)
        {
            this.stamp = stamp;
            this.source = source;
            this.temperature_c = temperature_c;
            this.humidity_pct = humidity_pct;
            this.pm25 = pm25;
            this.obstacle_dist_m = obstacle_dist_m;
            this.localization_score = localization_score;
            this.is_valid = is_valid;
        }

        public static SensorStateMsg Deserialize(MessageDeserializer deserializer) => new SensorStateMsg(deserializer);

        private SensorStateMsg(MessageDeserializer deserializer)
        {
            this.stamp = BuiltinInterfaces.TimeMsg.Deserialize(deserializer);
            deserializer.Read(out this.source);
            deserializer.Read(out this.temperature_c);
            deserializer.Read(out this.humidity_pct);
            deserializer.Read(out this.pm25);
            deserializer.Read(out this.obstacle_dist_m);
            deserializer.Read(out this.localization_score);
            deserializer.Read(out this.is_valid);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stamp);
            serializer.Write(this.source);
            serializer.Write(this.temperature_c);
            serializer.Write(this.humidity_pct);
            serializer.Write(this.pm25);
            serializer.Write(this.obstacle_dist_m);
            serializer.Write(this.localization_score);
            serializer.Write(this.is_valid);
        }

        public override string ToString()
        {
            return "SensorStateMsg: " +
            "\nstamp: " + stamp.ToString() +
            "\nsource: " + source.ToString() +
            "\ntemperature_c: " + temperature_c.ToString() +
            "\nhumidity_pct: " + humidity_pct.ToString() +
            "\npm25: " + pm25.ToString() +
            "\nobstacle_dist_m: " + obstacle_dist_m.ToString() +
            "\nlocalization_score: " + localization_score.ToString() +
            "\nis_valid: " + is_valid.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
