# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import robot_gateway_pb2 as robot__gateway__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in robot_gateway_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotGatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteTask = channel.unary_unary(
                '/robot.gateway.v1.RobotGateway/ExecuteTask',
                request_serializer=robot__gateway__pb2.ExecuteTaskRequest.SerializeToString,
                response_deserializer=robot__gateway__pb2.ExecuteTaskResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/robot.gateway.v1.RobotGateway/CancelTask',
                request_serializer=robot__gateway__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=robot__gateway__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/robot.gateway.v1.RobotGateway/EmergencyStop',
                request_serializer=robot__gateway__pb2.EmergencyStopRequest.SerializeToString,
                response_deserializer=robot__gateway__pb2.EmergencyStopResponse.FromString,
                _registered_method=True)
        self.ManualControl = channel.unary_unary(
                '/robot.gateway.v1.RobotGateway/ManualControl',
                request_serializer=robot__gateway__pb2.ManualControlRequest.SerializeToString,
                response_deserializer=robot__gateway__pb2.ManualControlResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/robot.gateway.v1.RobotGateway/GetStatus',
                request_serializer=robot__gateway__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=robot__gateway__pb2.RobotStatusResponse.FromString,
                _registered_method=True)
        self.StreamStatus = channel.unary_stream(
                '/robot.gateway.v1.RobotGateway/StreamStatus',
                request_serializer=robot__gateway__pb2.StreamStatusRequest.SerializeToString,
                response_deserializer=robot__gateway__pb2.RobotStatusResponse.FromString,
                _registered_method=True)


class RobotGatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExecuteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ManualControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteTask,
                    request_deserializer=robot__gateway__pb2.ExecuteTaskRequest.FromString,
                    response_serializer=robot__gateway__pb2.ExecuteTaskResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=robot__gateway__pb2.CancelTaskRequest.FromString,
                    response_serializer=robot__gateway__pb2.CancelTaskResponse.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=robot__gateway__pb2.EmergencyStopRequest.FromString,
                    response_serializer=robot__gateway__pb2.EmergencyStopResponse.SerializeToString,
            ),
            'ManualControl': grpc.unary_unary_rpc_method_handler(
                    servicer.ManualControl,
                    request_deserializer=robot__gateway__pb2.ManualControlRequest.FromString,
                    response_serializer=robot__gateway__pb2.ManualControlResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=robot__gateway__pb2.GetStatusRequest.FromString,
                    response_serializer=robot__gateway__pb2.RobotStatusResponse.SerializeToString,
            ),
            'StreamStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamStatus,
                    request_deserializer=robot__gateway__pb2.StreamStatusRequest.FromString,
                    response_serializer=robot__gateway__pb2.RobotStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot.gateway.v1.RobotGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot.gateway.v1.RobotGateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotGateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExecuteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.gateway.v1.RobotGateway/ExecuteTask',
            robot__gateway__pb2.ExecuteTaskRequest.SerializeToString,
            robot__gateway__pb2.ExecuteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.gateway.v1.RobotGateway/CancelTask',
            robot__gateway__pb2.CancelTaskRequest.SerializeToString,
            robot__gateway__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.gateway.v1.RobotGateway/EmergencyStop',
            robot__gateway__pb2.EmergencyStopRequest.SerializeToString,
            robot__gateway__pb2.EmergencyStopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ManualControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.gateway.v1.RobotGateway/ManualControl',
            robot__gateway__pb2.ManualControlRequest.SerializeToString,
            robot__gateway__pb2.ManualControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot.gateway.v1.RobotGateway/GetStatus',
            robot__gateway__pb2.GetStatusRequest.SerializeToString,
            robot__gateway__pb2.RobotStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot.gateway.v1.RobotGateway/StreamStatus',
            robot__gateway__pb2.StreamStatusRequest.SerializeToString,
            robot__gateway__pb2.RobotStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
